#!/bin/sh
cd /root/repo
git checkout $1
git log --all --numstat --date=short --pretty=format:'--%h--%ad--%aN' --no-renames >> /tmp/$1_log.log
mkdir /root/results/$1
java -jar /usr/src/code-maat/app-standalone.jar -l /tmp/$1_log.log -o /root/results/$1/$1_coupling.log.res -c git2 -a coupling
java -jar /usr/src/code-maat/app-standalone.jar -l /tmp/$1_log.log -o /root/results/$1/$1_revisions.log.res -c git2 -a revisions
